### ISSUE TITLE
Comment attachment should not imply storing syntax node location

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1021]
To demonstrate the issue, run the following script:

```javascript
var esprima = require('./esprima');
var code = '/* answer */ 42';
var tree = esprima.parse(code, { attachComment: true });
console.log(typeof tree.body[0].range);
```

The expected output is `undefined`. Since `range` option is not specified, it should default to `false` and hence every node will not have `range` property.

The current master branch produces the output `object` instead.

(Migrated from https://code.google.com/p/esprima/issues/detail?id=511)

**Comment by nzakas** [comment]
This is because comment attachment uses the range information to determine where to attach the comment. If we externalize comment attachment (#1068) then this problem is solved. :)

**Comment by ariya** [comment]
@nzakas I still don't see how. With a custom comment the attacher, you still need the location information (`range`) from the node.

**Comment by ariya** [comment]
This is now supported with the new comment handler via parser delegate.
