### ISSUE TITLE
Fails to parse dynamic imports in class methods

### ISSUE THREAD

**Issue by doplumi** [jquery/esprima#1945]
### Steps to reproduce

```js
esprima.parse(`
class C {
  f () {
    import('./page.js');
  }
}
`)
```

### Output
Error with stack trace referencing [this section of parser.ts](https://github.com/jquery/esprima/blob/master/src/parser.ts#L3470-L3472)

<details>
  <summary>Stack trace example</summary>
  <pre>ERROR in ./app/src/components/dd-app.js
Module build failed (from ./node_modules/minify-lit-html-loader/index.js):
Error: Line 8: Unexpected token
    at ErrorHandler.constructError (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:5028:27)
    at Parser.throwError (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:1936:34)
    at Parser.parseImportDeclaration (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:4795:19)
    at Parser.parseStatementListItem (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:3373:39)
    at Parser.parseFunctionSourceElements (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:4195:29)
    at Parser.isolateCoverGrammar (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:2269:37)
    at Parser.parsePropertyMethod (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:2441:26)
    at Parser.parsePropertyMethodFunction (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:2458:28)
    at Parser.parseClassElement (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:4628:79)
    at Parser.parseClassElementList (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:4665:33)
    at Parser.parseClassBody (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:4673:33)
    at Parser.parseClassDeclaration (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:4687:31)
    at Parser.parseStatementListItem (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:3382:39)
    at Parser.parseModule (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:4715:29)
    at Object.parse (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:122:38)
 @ ./app/src/entry.js 3:0-29
 @ multi (webpack)-dev-server/client?http://127.0.0.1:9002 webpack/hot/dev-server ./app/src/entry.js
</pre></details>

<details>
  <summary>Stack trace example if the import is `await`ed</summary>
<pre>ERROR in ./app/src/components/dd-app.js
Module build failed (from ./node_modules/minify-lit-html-loader/index.js):
Error: Line 9: Unexpected reserved word
    at ErrorHandler.constructError (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:5028:27)
    at Parser.unexpectedTokenError (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.throwUnexpectedToken (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:1995:21)
    at Parser.parsePrimaryExpression (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:2390:38)
    at Parser.inheritCoverGrammar (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseLeftHandSideExpressionAllowCall (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:2899:26)
    at Parser.inheritCoverGrammar (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseUpdateExpression (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:3004:26)
    at Parser.parseUnaryExpression (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:3048:26)
    at Parser.parseAwaitExpression (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:3027:30)
    at Parser.parseUnaryExpression (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:3045:26)
    at Parser.inheritCoverGrammar (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseExponentiationExpression (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:3054:26)
    at Parser.inheritCoverGrammar (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseBinaryExpression (/home/edge/src/webcomponents/minifier-dynamic-test/node_modules/esprima/dist/esprima.js:3089:26)
 @ ./app/src/entry.js 3:0-29
 @ multi (webpack)-dev-server/client?http://127.0.0.1:9002 webpack/hot/dev-server ./app/src/entry.js
</pre></details>

**Comment by doplumi** [comment]
Closing because I just noticed it's fixed in master, not released yet.

**Comment by vlaraort** [comment]
This still don't work, you can check it here:

http://esprima.org/demo/parse.html?code=class%20C%20%7B%0A%20%20f%20()%20%7B%0A%20%20%20%20import('.%2Fpage.js')%3B%0A%20%20%7D%0A%7D%0A
